# Advanced schemachange configuration with lists and complex variables
# Tests loops, macros, and advanced Jinja features

vars:
  database_name: "MY_DATABASE"
  schema_name: "ANALYTICS"
  environment: "DEV"
  
  # List variables for testing loops
  table_list:
    - name: "customers"
      columns:
        - {name: "id", type: "INTEGER", primary_key: true}
        - {name: "name", type: "VARCHAR(255)", not_null: true}
        - {name: "email", type: "VARCHAR(255)"}
        - {name: "phone", type: "VARCHAR(20)"}
        - {name: "created_at", type: "TIMESTAMP", default: "CURRENT_TIMESTAMP()"}
    - name: "orders"
      columns:
        - {name: "order_id", type: "INTEGER", primary_key: true}
        - {name: "customer_id", type: "INTEGER", not_null: true}
        - {name: "order_date", type: "TIMESTAMP", default: "CURRENT_TIMESTAMP()"}
        - {name: "total_amount", type: "DECIMAL(10,2)"}
        - {name: "status", type: "VARCHAR(50)", default: "'PENDING'"}
    - name: "products"
      columns:
        - {name: "product_id", type: "INTEGER", primary_key: true}
        - {name: "name", type: "VARCHAR(255)", not_null: true}
        - {name: "price", type: "DECIMAL(10,2)", not_null: true}
        - {name: "category", type: "VARCHAR(100)"}
        - {name: "in_stock", type: "BOOLEAN", default: "TRUE"}

  # List of environments for conditional logic
  environments: ["DEV", "TEST", "PROD"]
  
  # Configuration per environment
  dev_config:
    retention_days: 7
    backup_enabled: false
    monitoring_level: "basic"
  
  prod_config:
    retention_days: 90
    backup_enabled: true  
    monitoring_level: "advanced"

# Additional schemachange settings
config-folder: "."
root-folder: "."
modules-folder: "."
create-change-history-table: false